In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_digits

In [3]:
digit=load_digits()
x=(digit.data)
y=(digit.target)

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
x_Std=StandardScaler().fit_transform(x)
x_Std

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [6]:
from sklearn.model_selection import train_test_split

In [7]:

x_trainx_train, x_test, y_train, y_test = train_test_split(x , y, test_size=0.30, random_state = 101)

In [8]:
from sklearn.decomposition import PCA
pca = PCA(n_components=30)

In [9]:
PC = pca.fit_transform(x_Std)

In [10]:
prinDf = pd.DataFrame(data = PC)

In [11]:
prinDf

0         1         2         3         4         5         6   \
0     1.914213 -0.954501 -3.946027  2.028719 -0.267165  0.530293 -1.415419   
1     0.588981  0.924635  3.924751 -1.779848 -0.993429 -0.675641  1.878632   
2     1.302039 -0.317189  3.023330 -2.043374 -2.081113  0.935141 -1.296255   
3    -3.020771 -0.868771 -0.801737 -2.187043 -0.556804  0.727104  0.959706   
4     4.528949 -1.093479  0.973128 -1.419513 -1.715147  1.431538  1.073703   
5    -1.301889 -1.148184 -1.574620 -2.413642 -0.630997  0.740860  1.306945   
6     1.434222 -2.957846  2.831275 -0.076950  0.523038  0.010870  0.983689   
7     0.614240  5.462184  0.658245  0.434427  0.850185 -0.954040 -1.833938   
8    -1.098451 -0.665823 -0.041030 -1.102521 -0.900706  0.755165 -0.966427   
9    -0.537970 -0.777493 -1.568917 -0.759989 -0.121336 -0.600929  0.675046   
10    3.378759 -0.495768 -2.280889  1.429198  0.006556 -0.150571 -0.739251   
11    2.063345  2.016678  1.540464 -4.773144 -2.194267  0.344500  3.084508   
12   -1.937010 -1.815249  2.801344 -0.786535  3.025778 -0.384498 -0.647550   
13   -3.258077  2.149124 -1.615637 -1.798932 -0.745371  1.828753  0.763353   
14    5.458742  0.025134  0.182554 -0.119638 -0.541023  0.104736  1.082891   
15   -3.877036  2.606815  1.858513  5.454033  0.615500  0.988536  3.602327   
16    0.921351 -3.262238  3.401477 -3.227353  1.096473  0.081812 -0.573267   
17    1.415336  1.954479  0.560563 -0.368821 -1.302562 -1.883585 -1.063123   
18   -0.926523  2.253020  1.532954  0.111944 -1.640301  0.261328 -0.069360   
19   -2.370964 -2.931913 -0.381342 -3.232773  2.084170  0.545255 -0.615877   
20    2.001900 -1.319745 -2.570940  0.855338 -0.565546 -1.017689 -0.812101   
21    1.694878  2.075387  0.885988 -4.388595 -1.446111 -0.307260  3.643169   
22   -3.114570 -1.058977  2.451487 -0.547886  0.761770 -0.012663 -1.890019   
23   -1.469419  3.910389 -2.078325 -0.869930  0.203819  0.689515 -0.288342   
24    4.003333 -0.322216  0.587675 -2.740551 -1.513549  0.676095  2.088607   
25   -0.376722  0.525116  1.356026  3.106109  0.926277 -1.029388  1.450148   
26    1.286726 -3.969443  2.542968  0.936672  0.282397  0.352640  1.026746   
27    3.842317  3.478238 -1.569508 -1.675842 -0.274111 -0.345109 -0.150002   
28   -0.166538  0.934114  1.259169 -0.086545 -1.045668  0.362835 -0.878052   
29   -2.014425 -2.376843 -0.707880 -3.515266  1.168344  0.694355  0.206658   
...        ...       ...       ...       ...       ...       ...       ...   
1767  4.958573 -1.159638  0.645655 -1.495303 -1.408083  0.580246  2.222252   
1768  1.009034 -3.325936 -0.584423  0.907495 -0.665907  0.398985 -1.280025   
1769 -0.542841 -0.492982 -3.138861  0.952793  0.732345 -1.169329  1.899888   
1770 -3.314655  1.510567 -0.820061 -1.838153 -1.474758  1.442530  2.178361   
1771  2.128214 -2.822365  3.623385 -1.087841 -0.085810  0.389335  1.443185   
1772 -1.814029  1.197999 -3.113651 -1.063790 -1.806721  0.021207  1.295099   
1773  1.374679 -4.417770  0.544580  0.931148  1.151834 -0.342586  0.125651   
1774  0.762952  0.643400  3.119034 -0.449237 -2.038268 -0.268266 -0.225303   
1775 -0.433044  3.216015  2.011145 -0.229275 -1.509354 -1.166748 -2.852311   
1776 -0.525868 -1.154642 -1.889807  0.953323  0.807100 -1.084774  1.495678   
1777  5.106682 -0.289142  0.341408 -1.773523 -2.469455  1.596714  0.885069   
1778  5.900098 -1.710240  1.858906  0.171259 -4.529266  4.714868  0.440436   
1779  1.597139  4.676428  0.469293 -0.503399 -0.074192 -1.780247 -2.551095   
1780 -5.137834 -0.191051  2.223949  2.046434 -0.885022  3.406991 -0.342035   
1781 -1.416099 -1.031484  1.196093  0.841534 -2.197930  2.483130  0.573133   
1782 -4.272989 -1.355841  3.059700  0.367674  1.045050  0.747281  0.006478   
1783 -3.136887 -1.411701  2.238423 -0.085146  0.779765  0.689988 -1.289866   
1784  1.568544 -0.438604 -1.840602 -0.847228  0.413589 -1.193676  2.474052   
1785  0.058277  1.978136  1.807586  1.282999 -1.856859 -0.846995 -3.167472   
1786 -0.711455  0.253346 -2.934786

In [12]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444415, 0.06498408, 0.04860155,
       0.0421412 , 0.03942083, 0.03389381, 0.02998221, 0.02932002,
       0.02781805, 0.02577055, 0.02275303, 0.0222718 , 0.02165229,
       0.01914166, 0.01775527, 0.01638066, 0.01596452, 0.01489179,
       0.01347945, 0.01271866, 0.01165807, 0.01057401, 0.00974953,
       0.00943525, 0.00862486, 0.00836611, 0.00796927, 0.00746011])

In [13]:
from sklearn.linear_model import LogisticRegression
prinDf_train,prinDf_test,y_train,y_test = train_test_split(prinDf,y,test_size = 0.3)
m=LogisticRegression()
m.fit(prinDf_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [14]:
pred=m.predict(prinDf_test)
pred

array([4, 5, 9, 5, 0, 5, 9, 9, 1, 2, 0, 5, 6, 2, 9, 1, 6, 4, 5, 2, 0, 3,
       9, 6, 4, 3, 1, 4, 6, 8, 4, 8, 0, 3, 3, 0, 3, 8, 7, 9, 2, 3, 2, 4,
       5, 0, 1, 4, 8, 9, 5, 6, 3, 6, 9, 6, 7, 5, 3, 5, 3, 0, 5, 8, 3, 3,
       5, 9, 7, 6, 5, 1, 8, 1, 4, 1, 7, 5, 2, 3, 0, 9, 5, 0, 2, 0, 7, 7,
       6, 9, 3, 9, 5, 5, 4, 6, 5, 5, 8, 8, 5, 7, 0, 1, 9, 2, 0, 1, 3, 6,
       7, 1, 4, 5, 4, 3, 1, 1, 7, 2, 0, 7, 7, 4, 7, 2, 5, 2, 1, 4, 1, 9,
       3, 2, 3, 9, 4, 0, 8, 3, 8, 3, 2, 6, 3, 7, 9, 0, 4, 6, 1, 0, 4, 9,
       7, 0, 9, 2, 1, 6, 2, 7, 8, 5, 7, 3, 3, 0, 2, 4, 9, 2, 0, 9, 3, 8,
       1, 4, 0, 4, 7, 7, 8, 6, 8, 9, 6, 6, 9, 4, 8, 1, 7, 4, 9, 6, 9, 1,
       3, 1, 2, 8, 2, 9, 3, 1, 4, 1, 9, 0, 1, 1, 5, 3, 6, 5, 9, 7, 1, 7,
       1, 9, 2, 3, 7, 8, 1, 5, 4, 4, 7, 0, 1, 9, 5, 0, 0, 7, 9, 0, 4, 2,
       4, 4, 7, 8, 4, 4, 4, 6, 2, 7, 8, 5, 8, 5, 6, 6, 3, 1, 2, 7, 6, 8,
       6, 3, 9, 5, 4, 5, 4, 1, 2, 9, 2, 7, 4, 4, 7, 8, 6, 1, 9, 0, 2, 5,
       4, 8, 8, 0, 2, 1, 4, 8, 8, 6, 9, 9, 2, 3, 1,

In [15]:
from sklearn import metrics
metrics.accuracy_score(y_test,pred)

0.9425925925925925

In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        46
          1       0.91      0.95      0.93        55
          2       0.96      0.98      0.97        53
          3       1.00      0.84      0.91        62
          4       0.97      1.00      0.98        59
          5       0.96      1.00      0.98        53
          6       0.94      0.94      0.94        52
          7       0.98      0.94      0.96        52
          8       0.80      0.88      0.84        50
          9       0.91      0.91      0.91        58

avg / total       0.95      0.94      0.94       540



In [17]:
from sklearn.metrics import confusion_matrix

In [18]:
confusion_matrix(y_test,pred)

array([[46,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 52,  0,  0,  0,  0,  2,  0,  0,  1],
       [ 0,  0, 52,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  1, 52,  0,  1,  0,  1,  5,  2],
       [ 0,  0,  0,  0, 59,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 53,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0, 49,  0,  2,  0],
       [ 0,  0,  0,  0,  1,  0,  0, 49,  0,  2],
       [ 0,  4,  1,  0,  0,  0,  1,  0, 44,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  4, 53]], dtype=int64)