In [40]:
import sklearn  as preprocessing
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn import model_selection
from sklearn import  tree
from sklearn.metrics import confusion_matrix

In [3]:
df=pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data")
df

B  1  1.1  1.2  1.3
0    R  1    1    1    2
1    R  1    1    1    3
2    R  1    1    1    4
3    R  1    1    1    5
4    R  1    1    2    1
5    R  1    1    2    2
6    R  1    1    2    3
7    R  1    1    2    4
8    R  1    1    2    5
9    R  1    1    3    1
10   R  1    1    3    2
11   R  1    1    3    3
12   R  1    1    3    4
13   R  1    1    3    5
14   R  1    1    4    1
15   R  1    1    4    2
16   R  1    1    4    3
17   R  1    1    4    4
18   R  1    1    4    5
19   R  1    1    5    1
20   R  1    1    5    2
21   R  1    1    5    3
22   R  1    1    5    4
23   R  1    1    5    5
24   L  1    2    1    1
25   B  1    2    1    2
26   R  1    2    1    3
27   R  1    2    1    4
28   R  1    2    1    5
29   B  1    2    2    1
..  .. ..  ...  ...  ...
594  L  5    4    5    1
595  L  5    4    5    2
596  L  5    4    5    3
597  B  5    4    5    4
598  R  5    4    5    5
599  L  5    5    1    1
600  L  5    5    1    2
601  L  5    5    1    3
602  L  5    5    1    4
603  L  5    5    1    5
604  L  5    5    2    1
605  L  5    5    2    2
606  L  5    5    2    3
607  L  5    5    2    4
608  L  5    5    2    5
609  L  5    5    3    1
610  L  5    5    3    2
611  L  5    5    3    3
612  L  5    5    3    4
613  L  5    5    3    5
614  L  5    5    4    1
615  L  5    5    4    2
616  L  5    5    4    3
617  L  5    5    4    4
618  L  5    5    4    5
619  L  5    5    5    1
620  L  5    5    5    2
621  L  5    5    5    3
622  L  5    5    5    4
623  B  5    5    5    5

[624 rows x 5 columns]

In [4]:
df.shape

(624, 5)

In [124]:
df.head(5)

B  1  1.1  1.2  1.3
0  R  1    1    1    2
1  R  1    1    1    3
2  R  1    1    1    4
3  R  1    1    1    5
4  R  1    1    2    1

In [13]:
x=df.drop(["B"],axis=1)
y=df["B"]

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [112]:
model=tree.DecisionTreeClassifier(min_samples_split=55)
model.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=55,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [113]:
pred=model.predict(x_test)


In [114]:
metrics.accuracy_score(y_test,pred)

0.7925531914893617

In [125]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        10
          L       0.73      0.87      0.79        82
          R       0.86      0.81      0.83        96

avg / total       0.76      0.79      0.77       188



C:\Users\delll\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [126]:
confusion_matrix(y_test,pred)

array([[ 0,  8,  2],
       [ 0, 71, 11],
       [ 0, 18, 78]], dtype=int64)

In [127]:
model1=tree.DecisionTreeClassifier(criterion='entropy',min_samples_split=55)
model1.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=55,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [130]:
pred1=model1.predict(x_test)

In [131]:
metrics.accuracy_score(y_test,pred1)

0.7606382978723404

In [132]:
print(classification_report(y_test,pred1))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        10
          L       0.70      0.88      0.78        82
          R       0.84      0.74      0.78        96

avg / total       0.73      0.76      0.74       188



C:\Users\delll\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [133]:
confusion_matrix(y_test,pred1)

array([[ 0,  6,  4],
       [ 0, 72, 10],
       [ 0, 25, 71]], dtype=int64)

In [143]:
from sklearn .ensemble import RandomForestClassifier
model2=RandomForestClassifier(max_depth=38)
model2.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=38, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [144]:
pred2=model2.predict(x_test)

In [145]:
metrics.accuracy_score(y_test,pred2)

0.8138297872340425

In [146]:
print(classification_report(y_test,pred2))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        10
          L       0.86      0.88      0.87        82
          R       0.93      0.84      0.89        96

avg / total       0.85      0.81      0.83       188



In [147]:
confusion_matrix(y_test,pred2)

array([[ 0,  5,  5],
       [ 9, 72,  1],
       [ 8,  7, 81]], dtype=int64)

In [149]:
model3=RandomForestClassifier(criterion='entropy',max_depth=38)
model3.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=38, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [150]:
pred3=model3.predict(x_test)

In [151]:
metrics.accuracy_score(y_test,pred3)

0.851063829787234

In [152]:
print(classification_report(y_test,pred3))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        10
          L       0.88      0.90      0.89        82
          R       0.95      0.90      0.92        96

avg / total       0.87      0.85      0.86       188



In [153]:
confusion_matrix(y_test,pred3)

array([[ 0,  6,  4],
       [ 7, 74,  1],
       [ 6,  4, 86]], dtype=int64)