In [1]:
import sklearn  as preprocessing
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn import model_selection
from sklearn.metrics import confusion_matrix

In [2]:
df=pd.read_csv("C:/Users/delll/Desktop/train.csv",header=None)
df.head()


0                      1  \
0  0   '591764470197723137'   
1  0   '591779538046218240'   
2  0   '591728244925210624'   
3  0   '591774433926193152'   
4  0   '591764472651386882'   

                                                   2  \
0   '#Nepal #news Adding to Bhutanese Refugees Bh...   
1   "The massacre of people's movement says peace...   
2                                        "I'm lonely   
3   '#nepal #news 6 billion collection collection...   
4   '#Nepal #news Indian proposal to crash airpor...   

                                                   3                    4  \
0                                                NaN                  NaN   
1                                                NaN                  NaN   
2   maybe you're going to die without closing the...   I'm going to die."   
3                                                NaN                  NaN   
4                                                NaN                  NaN   

     5    6    7    8  
0  NaN  NaN  NaN  NaN  
1  NaN  NaN  NaN  NaN  
2  NaN  NaN  NaN  NaN  
3  NaN  NaN  NaN  NaN  
4  NaN  NaN  NaN  NaN

In [3]:
df.isnull().sum()

0        0
1        0
2        0
3    15852
4    17419
5    17927
6    18049
7    18075
8    18085
dtype: int64

In [4]:
df=df.fillna(value="")
df.head()

0                      1  \
0  0   '591764470197723137'   
1  0   '591779538046218240'   
2  0   '591728244925210624'   
3  0   '591774433926193152'   
4  0   '591764472651386882'   

                                                   2  \
0   '#Nepal #news Adding to Bhutanese Refugees Bh...   
1   "The massacre of people's movement says peace...   
2                                        "I'm lonely   
3   '#nepal #news 6 billion collection collection...   
4   '#Nepal #news Indian proposal to crash airpor...   

                                                   3                    4 5 6  \
0                                                                               
1                                                                               
2   maybe you're going to die without closing the...   I'm going to die."       
3                                                                               
4                                                                               

  7 8  
0      
1      
2      
3      
4

In [5]:
df["texts"] =df[2].map(str) + df[3].map(str)+df[4].map(str) + df[5].map(str)+df[6].map(str) + df[7].map(str)+df[8].map(str)


In [6]:
df.head()

0                      1  \
0  0   '591764470197723137'   
1  0   '591779538046218240'   
2  0   '591728244925210624'   
3  0   '591774433926193152'   
4  0   '591764472651386882'   

                                                   2  \
0   '#Nepal #news Adding to Bhutanese Refugees Bh...   
1   "The massacre of people's movement says peace...   
2                                        "I'm lonely   
3   '#nepal #news 6 billion collection collection...   
4   '#Nepal #news Indian proposal to crash airpor...   

                                                   3                    4 5 6  \
0                                                                               
1                                                                               
2   maybe you're going to die without closing the...   I'm going to die."       
3                                                                               
4                                                                               

  7 8                                              texts  
0       '#Nepal #news Adding to Bhutanese Refugees Bh...  
1       "The massacre of people's movement says peace...  
2       "I'm lonely maybe you're going to die without...  
3       '#nepal #news 6 billion collection collection...  
4       '#Nepal #news Indian proposal to crash airpor...

In [7]:
df.drop(columns=[2,3,4,5,6,7,8],axis=1)

0                      1  \
0      0   '591764470197723137'   
1      0   '591779538046218240'   
2      0   '591728244925210624'   
3      0   '591774433926193152'   
4      0   '591764472651386882'   
5      0   '591751543025569793'   
6      0   '591727216267890688'   
7      0   '591739000001470464'   
8      0   '591753691084038146'   
9      0   '591747428358881282'   
10     0   '591760691872169985'   
11     0   '591770916360560640'   
12     0   '591751403221098496'   
13     0   '591726847219478528'   
14     0   '591714830446301184'   
15     0   '591732037159030785'   
16     0   '591672103788621824'   
17     0   '591673483832270848'   
18     0   '591729367132188672'   
19     0   '591746927269523458'   
20     0   '591729090832437248'   
21     0   '591752371241267200'   
22     0   '591747039844667392'   
23     0   '591741541514772480'   
24     0   '591742811784884225'   
25     0   '591744262917660674'   
26     0   '591773192907202560'   
27     0   '591744687058198528'   
28     0   '591737214868021248'   
29     0   '591747765916413952'   
...   ..                    ...   
18056  2   '592642423265894401'   
18057  2   '592643848385335296'   
18058  2   '592645149282340864'   
18059  2   '592643776625123328'   
18060  2   '592648262315876353'   
18061  2   '592648593384738816'   
18062  2   '592651886215430144'   
18063  2   '592652635439697921'   
18064  2   '592652513360220160'   
18065  2   '592660156183371776'   
18066  2   '592661430979141633'   
18067  2   '592663760919232512'   
18068  2   '592666086690189313'   
18069  2   '592667760880132096'   
18070  2   '592670897477165059'   
18071  2   '592674856279355393'   
18072  2   '592677666144288769'   
18073  2   '592677515514269696'   
18074  2   '592679798817816576'   
18075  2   '592682158814339072'   
18076  2   '592684009563549696'   
18077  2   '592683279188361217'   
18078  2   '592694344655699968'   
18079  2   '592697492422144000'   
18080  2   '592696857815572481'   
18081  2   '592697535271174145'   
18082  2   '592697135390416899'   
18083  2   '592698989507715075'   
18084  1     '5644654646545646'   
18085  2      '543533654345435'   

                                                   texts  
0       '#Nepal #news Adding to Bhutanese Refugees Bh...  
1       "The massacre of people's movement says peace...  
2       "I'm lonely maybe you're going to die without...  
3       '#nepal #news 6 billion collection collection...  
4       '#Nepal #news Indian proposal to crash airpor...  
5       'God also ran away for money after the poor l...  
6                     'Someone feels like a tile to see'  
7       'The boys began to write English passage. I -...  
8       "I will not go away it's not going to be brok...  
9                                           'Gaurab Sir'  
10      'Nepal is shaken as a cheat and why do not th...  
11      'Baba Ramdev to clean Bagramati Ray in Kiripu...  
12      'Seventh Asian Asian Games Madras Bastasta wo...  
13      "See What's New Updates Get Started in the So...  
14      'original one by Anjum Rahbar I used to flame...  
15      "Let's compromise I do not steal your temper ...  
16      'Gajendra received a diary. Extremely Beautif...  
17      "Nepal's Autism Children cooperate in Korea N...  
18                                        'Good morning'  
19                                              'Sheikh'  
20      'The photo should not be sent when you are si...  
21      'You are the queen of my castle the queen of ...  
22                                              'Hunter'  
23                                 'Can you be a friend'  
24      'If I am to wrap with you then I can learn to...  
25      'Just ask the right to ask all of these Tweet...  
26               'Good day all the friends of Jai Nepal'  
27                           'There is a lot of sulfony'  
28      'General Knowledge Get all quiz in Nepali lan...  
29      'All of these floors are currently active .Th...  
...    

In [8]:
df.shape

(18086, 10)

In [9]:
df["texts"][0]

" '#Nepal #news Adding to Bhutanese Refugees Bhutanese citizens of Nepalese origin still refrain from leaving their bags.'"

In [10]:
from nltk.corpus import stopwords
import nltk
nltk.download("stopwords")
stopword=set(stopwords.words("english"))
df['texts']=df['texts'].apply(lambda x:" ".join([word for word in x.split() if word not in (stopword)]))


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\delll\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [11]:
from sklearn.feature_extraction import  text

In [12]:
vect=text.TfidfVectorizer()

In [13]:
X=vect.fit(df["texts"])

In [14]:
abc=X.transform(df["texts"])

In [15]:
abc.shape

(18086, 17081)

In [16]:
vect.vocabulary_

{u'raining': 11968,
 u'four': 5857,
 u'woods': 16380,
 u'hanging': 6568,
 u'centimeter': 2878,
 u'aggression': 954,
 u'increase': 7311,
 u'farmcrisis': 5499,
 u'quadruple': 11856,
 u'israaid': 7658,
 u'sinking': 13684,
 u'fashiondesigner': 5513,
 u'pierce': 11169,
 u'xa0loss': 16518,
 u'bishman': 2309,
 u'screaming': 13146,
 u'disturb': 4509,
 u'basics': 1920,
 u'wooden': 16379,
 u'wednesday': 16200,
 u'viable': 15906,
 u'taluafact': 14592,
 u'commented': 3299,
 u'fecu': 5565,
 u'specially': 13963,
 u'reengineering': 12232,
 u'obfuckingviously': 10439,
 u'relieving': 12329,
 u'thunder': 14983,
 u'cooking': 3567,
 u'resilienc': 12460,
 u'gujarati': 6435,
 u'replaced': 12389,
 u'hallucinating': 6532,
 u'shocks': 13524,
 u'pmoindia': 11293,
 u'27m': 209,
 u'lgbt': 8665,
 u'china': 3046,
 u'cult': 3783,
 u'kids': 8278,
 u'desuups': 4195,
 u'elaborate': 4991,
 u'climbed': 3170,
 u'controversy': 3543,
 u'natures': 9973,
 u'aapkilledfarmer': 660,
 u'climber': 3171,
 u'592523079911256064': 483

In [17]:
df.head()

0                      1  \
0  0   '591764470197723137'   
1  0   '591779538046218240'   
2  0   '591728244925210624'   
3  0   '591774433926193152'   
4  0   '591764472651386882'   

                                                   2  \
0   '#Nepal #news Adding to Bhutanese Refugees Bh...   
1   "The massacre of people's movement says peace...   
2                                        "I'm lonely   
3   '#nepal #news 6 billion collection collection...   
4   '#Nepal #news Indian proposal to crash airpor...   

                                                   3                    4 5 6  \
0                                                                               
1                                                                               
2   maybe you're going to die without closing the...   I'm going to die."       
3                                                                               
4                                                                               

  7 8                                              texts  
0      '#Nepal #news Adding Bhutanese Refugees Bhutan...  
1      "The massacre people's movement says peace con...  
2      "I'm lonely maybe going die without closing ci...  
3      '#nepal #news 6 billion collection collection ...  
4      '#Nepal #news Indian proposal crash airport cr...

In [18]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [19]:
text=pd.DataFrame(df["texts"])

In [20]:
y= pd.DataFrame(df[0])

In [21]:
df_new=SelectKBest(chi2,k=2).fit_transform(abc,y)

In [22]:
df_new.shape

(18086, 2)

In [23]:
from sklearn.model_selection import StratifiedShuffleSplit

In [24]:
shuffle=StratifiedShuffleSplit(n_splits=9,random_state=6)

In [25]:
y=y.values.reshape(18086)

In [39]:
for train_index,test_index in shuffle.split(df_new,y):
    X_train,X_test=df_new[train_index],df_new[test_index]
    y_train,y_test=y[train_index],y[test_index]

In [40]:
from sklearn.naive_bayes import GaussianNB


In [48]:
model=GaussianNB()
model.fit(X_train.todense(),y_train)

GaussianNB(priors=None)

In [50]:
pred=model.predict(X_test.todense())

In [86]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score

In [87]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.97      0.98      0.98      1723
          1       0.40      0.10      0.16        20
          2       0.37      0.39      0.38        66

avg / total       0.94      0.95      0.94      1809



In [88]:
confusion_matrix(y_test,pred)

array([[1685,    1,   37],
       [  10,    2,    8],
       [  38,    2,   26]], dtype=int64)

In [89]:
metrics.accuracy_score(pred,y_test)

0.9469320066334992

In [90]:
from sklearn.naive_bayes import MultinomialNB

In [91]:
model1=MultinomialNB()
model1.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [92]:
pred1=model1.predict(X_test)

In [93]:
metrics.accuracy_score(pred1,y_test)

0.9524599226091763

In [94]:
print(classification_report(y_test,pred1))

             precision    recall  f1-score   support

          0       0.95      1.00      0.98      1723
          1       0.00      0.00      0.00        20
          2       0.00      0.00      0.00        66

avg / total       0.91      0.95      0.93      1809



C:\Users\delll\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [95]:
confusion_matrix(y_test,pred1)

array([[1723,    0,    0],
       [  20,    0,    0],
       [  66,    0,    0]], dtype=int64)

In [96]:
from sklearn.svm import SVC

In [97]:
svc1=SVC(kernel="poly")

svc1.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [98]:
predict1=svc1.predict(x_test)

In [99]:
predict1


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [100]:
print(classification_report(y_test,predict1))

             precision    recall  f1-score   support

          0       0.95      1.00      0.98      1723
          1       0.00      0.00      0.00        20
          2       0.00      0.00      0.00        66

avg / total       0.91      0.95      0.93      1809



C:\Users\delll\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [101]:
metrics.accuracy_score(y_test,predict1)

0.9524599226091763

In [102]:
confusion_matrix(y_test,predict1)

array([[1723,    0,    0],
       [  20,    0,    0],
       [  66,    0,    0]], dtype=int64)

In [131]:

#decision tree
from sklearn.tree import DecisionTreeClassifier

DTree = DecisionTreeClassifier()

DTree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [122]:
pre_DTree = DTree.predict(X_test)

In [123]:
print(classification_report(pre_DTree,y_test))

             precision    recall  f1-score   support

          0       0.99      0.96      0.98      1771
          1       0.15      0.60      0.24         5
          2       0.24      0.48      0.32        33

avg / total       0.97      0.95      0.96      1809



In [125]:
print(confusion_matrix(pre_DTree,y_test))

[[1706   16   49]
 [   1    3    1]
 [  16    1   16]]


In [129]:


print(accuracy_score(pre_DTree,y_test))

0.9535655058043118


In [130]:
f1_DTree = f1_score(pre_DTree,y_test,average="weighted")
print(f1_DTree)

0.9625778968373381


In [132]:
#random forest
from sklearn.ensemble import RandomForestClassifier

RandT = RandomForestClassifier(n_estimators=100,n_jobs=2,random_state=7)

RandT.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
            oob_score=False, random_state=7, verbose=0, warm_start=False)

In [104]:
pre_RandT = RandT.predict(X_test)

In [105]:
print(classification_report(pre_RandT,y_test))
             

             precision    recall  f1-score   support

          0       0.99      0.96      0.98      1770
          1       0.15      0.50      0.23         6
          2       0.24      0.48      0.32        33

avg / total       0.97      0.95      0.96      1809



In [106]:
print(confusion_matrix(pre_RandT,y_test))

[[1705   16   49]
 [   2    3    1]
 [  16    1   16]]


In [83]:
metrics.accuracy_score(pre_RandT,y_test)

0.953012714206744

In [107]:
f1_RandT = f1_score(pre_RandT,y_test,average="weighted")
print(f1_RandT)

0.961853443632923


In [108]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [109]:
estimater = []
model4= LogisticRegression()
estimater.append(("Logistic",model4))
model5 = KMeans()
estimater.append(("KMeans",model5))
model6 = SVC(kernel="rbf")
estimater.append(("SVC",model6))
model7 = GaussianNB()
estimater.append(("Gaussian",model7))
model8 =  KNeighborsClassifier()
estimater.append(("KNN",model8))

In [110]:
Voti = VotingClassifier(estimater)

In [111]:
Voti.fit(X_train.todense(),y_train)

VotingClassifier(estimators=[('Logistic', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)), ('KMeans...owski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [112]:
pre_Voti = Voti.predict(X_test.todense())

C:\Users\delll\Anaconda2\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [113]:
print(classification_report(pre_Voti,y_test))

             precision    recall  f1-score   support

          0       0.99      0.96      0.98      1785
          1       0.00      0.00      0.00         0
          2       0.18      0.50      0.27        24

avg / total       0.98      0.95      0.97      1809



C:\Users\delll\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [114]:
print(confusion_matrix(pre_Voti,y_test))

[[1711   20   54]
 [   0    0    0]
 [  12    0   12]]


In [115]:
print(accuracy_score(pre_Voti,y_test))

0.9524599226091763


In [117]:
f1_Voti = f1_score(pre_Voti,y_test,average="weighted")
print(f1_Voti)

0.966080720179667


C:\Users\delll\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
